routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/category', 'CategoryController', ['as'=>'admin']);
    Route::resource('/article', 'ArticleController', ['as'=>'admin']);
    Route::resource('/tag', 'TagController', ['as'=>'admin']);
});

Route::get('/', function () {
    return view('layouts.main');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search/{searchKey}', 'HomeController@search');


Route::get('/login/{social}','Auth\LoginController@socialLogin')
    ->where('social','twitter|facebook|google');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')
    ->where('social','twitter|facebook|google');

Route::get('/user/activation/{token}', 'Auth\RegisterController@userActivation');

/*Route::get('/search', function (Request $request) {
    $result = App\Tag::search($request->search)->get();
    return view('layouts.result', compact('result'));
});*/

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Tag extends Model
{

    use Searchable;

    public function searchableAs()
    {
        return 'tags';
    }

    protected $fillable = ['name'];

    public function articles()
    {
        return $this->belongsToMany('App\Article')->withTimestamps();
    }

    public function scopeLastTags($query)
    {
        return $query->orderBy('created_at', 'desc')->get();
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.tags.index', [
            'tags' => Tag::paginate(50)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create', [
            'tag'   => [],
            'delimiter'  => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Tag::create($request->all());
        return redirect()->route('admin.tag.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', [
            'tag'   => $tag,
            'delimiter'  => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $tag->update($request);

        return redirect()->route('admin.tag.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->articles()->detach();
        $tag->delete();

        return redirect()->route('admin.tag.index');
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
            @slot('title') Создание тега @endslot
            @slot('parent') Главная @endslot
            @slot('active') теги @endslot
        @endcomponent

        <hr />

        <form class="form-horizontal" action="{{route('admin.tag.store')}}" method="post">
            {!! csrf_field() !!}

            {{-- Form include --}}
            @include('admin.tags.partials.form')

        </form>
    </div>

@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
            @slot('title') Редактирование тега @endslot
            @slot('parent') Главная @endslot
            @slot('active') теги @endslot
        @endcomponent

        <hr />

        <form class="form-horizontal"
              action="{{route('admin.tag.update', $tag)}}" method="post">
            <input type="hidden" value="put" name="_method">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.tags.partials.form')

        </form>
    </div>

@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Список тегов @endslot
            @slot('parent') Главная @endslot
            @slot('active') Теги @endslot
        @endcomponent

        <hr>
        <a href="{{route('admin.tag.create')}}" class="btn btn-primary pull-right">
            <i class="fa fa-plus-square-o"></i> Создать тег
        </a>
        <table class="table table-striped">
            <thead>
            <th>Наименование</th>
            <th class="text-right">Действие</th>
            </thead>
            <tbody>
            @forelse($tags as $tag)
                <tr>
                    <td>{{$tag->name}}</td>
                    <td class="text-right">
                        <form action="{{route('admin.tag.destroy', $tag)}}"
                              onsubmit="if(confirm('Удалить?')){ return true }else{ return false }"
                              method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field() }}

                            <a href="{{route('admin.tag.edit', $tag)}}" class="btn btn-default">
                                <i class="fa fa-edit"></i>
                            </a>

                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" class="text-center"><h2>Данныйе отсуствуют</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="3">
                    <ul class="pagination pull-right">
                        {{$tags->links()}}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
@endsection